table delivery_routes_clean
	lineageTag: 40f4e706-9b29-43ad-aae1-5db13944165b

	measure 'Total Deliveries' = ```
			
			    COUNTROWS('delivery_routes_clean')
			```
		formatString: 0
		lineageTag: 897fdd13-ef42-49a7-8cc3-70608df1c760

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Avg Delivery Time (Mins)' = ```
			
			    AVERAGE(('delivery_routes_clean'[delivery_duration_minutes]))
			```
		formatString: 0
		lineageTag: b2114c7f-2eab-4c88-badb-ad626347dfd1

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Total Fuel Anomalies' = ```
			
			    CALCULATE(
			        [Total Deliveries],
			        'delivery_routes_clean'[fuel_status] <> "Valid"
			    )
			```
		formatString: 0
		lineageTag: a070ebde-69cb-4d36-a15b-efcf6de9318d

	column route_id
		dataType: int64
		formatString: 0
		lineageTag: f3466d79-03d9-43ce-bb4b-3d5be3a1c8c0
		summarizeBy: sum
		sourceColumn: route_id

		annotation SummarizationSetBy = Automatic

	column driver_id
		dataType: int64
		formatString: 0
		lineageTag: e1cdea72-1e93-4877-8397-4b4bc52f5e95
		summarizeBy: none
		sourceColumn: driver_id

		annotation SummarizationSetBy = Automatic

	column vehicle_id
		dataType: int64
		formatString: 0
		lineageTag: e9f2e5f5-7abf-4e59-805d-382a1422adc6
		summarizeBy: none
		sourceColumn: vehicle_id

		annotation SummarizationSetBy = Automatic

	column dispatch_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: a75b1bcd-d2ec-42da-bc69-8cdbd476d2a2
		summarizeBy: none
		sourceColumn: dispatch_timestamp

		variation Variation
			isDefault
			relationship: 4ecd9f4c-55cd-4a96-802d-13c1e21b39d5
			defaultHierarchy: LocalDateTable_cecd84d7-5cc7-40e6-9323-d90ed1af0f1a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column delivery_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: 107ada67-2c49-4f2d-98b6-269402b24f3e
		summarizeBy: none
		sourceColumn: delivery_timestamp

		variation Variation
			isDefault
			relationship: 9e46ce08-466d-43d8-a382-4f013f627d88
			defaultHierarchy: LocalDateTable_4800bb4b-ead7-4deb-beb6-b574a6cece0e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column distance_miles
		dataType: double
		lineageTag: addb2a39-5b5e-45b8-a37c-ee5698ba6155
		summarizeBy: sum
		sourceColumn: distance_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fuel_used_gallons
		dataType: double
		lineageTag: 369c5b79-60b0-493c-a13c-1129bb896c97
		summarizeBy: sum
		sourceColumn: fuel_used_gallons

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column delivery_duration_minutes
		dataType: double
		lineageTag: a91bcd00-697e-4de9-8744-60b44fbe425c
		summarizeBy: sum
		sourceColumn: delivery_duration_minutes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column timestamp_status
		dataType: string
		lineageTag: 61b094fb-5620-4ce9-8a13-7ae9178e6950
		summarizeBy: none
		sourceColumn: timestamp_status

		annotation SummarizationSetBy = Automatic

	column fuel_status
		dataType: string
		lineageTag: 9b7b219b-d743-434f-95fd-82800b92d440
		summarizeBy: none
		sourceColumn: fuel_status

		annotation SummarizationSetBy = Automatic

	partition delivery_routes_clean = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost", "postgres"),
				    portfolio_project_5_delivery_routes_clean = Source{[Schema="portfolio_project_5",Item="delivery_routes_clean"]}[Data]
				in
				    portfolio_project_5_delivery_routes_clean

	changedProperty = Name

	annotation PBI_ResultType = Table

